# Generated by Django 4.2.6 on 2023-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Teacher_app_images/')),
                ('students', models.ManyToManyField(related_name='teachers', to='Student.student')),
            ],
        ),
    ]
