# Generated by Django 4.2.6 on 2023-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_certificate_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
