# Generated by Django 4.2.6 on 2023-10-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_has_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_certificate',
        ),
    ]
